### ISSUE TITLE
Schema evolution support

### ISSUE THREAD

**Issue by oleksmir** [linkedin/goavro#166] opened 2019-06-11 18:49 UTC
It would be great if schema evolution would be supported. Currently decoding old messages using new schema leads to `error decoding new field bytes: short buffer`.

**Comment by karrick** [comment] 2019-06-11 20:03
Schema evolution _is_ supported and should be working. If you are receiving this error, please provide additional information, namely the initial schema, the modified schema, and most importantly, how you are trying to read the data.

Also, I just did a code search looking for "error decoding", "new field", and "field bytes" and could not find those strings anywhere in the current code base. Could you additionally provide the error message that you received, because I suspect the message mentioned above is from the code that imports and uses `goavro`.

**Comment by oleksmir** [comment] 2019-06-12 04:17
Old schema: 
```
{
  "type" : "record",
  "name" : "User",
  "namespace" : "com.github.oleksmir.goavro",
  "fields" : [ {
    "name" : "id",
    "type" : "string",
    "default" : "test_id"
  }, {
    "name" : "age",
    "type" : "int",
    "default" : 100
  } ]
}
```
New schema: 
```
{
  "type" : "record",
  "name" : "User",
  "namespace" : "com.github.oleksmir.goavro",
  "fields" : [ {
    "name" : "id",
    "type" : "string",
    "default" : "test_id"
  }, {
    "name" : "age",
    "type" : "int",
    "default" : 100
  }, {
    "name" : "firstName",
    "type" : "string",
    "default" : "test_first_name"
  }, {
    "name" : "lastName",
    "type" : "string",
    "default" : "test_last_name"
  }, {
    "name" : "info",
    "type" : "string",
    "default" : "test_info"
  } ]
}
```
I am trying to read old messages using new schema:
```
file, err := os.Open(newSchemaFilePath)
assert.Nil(t, err)
	schemaText, err := ioutil.ReadAll(file)
	assert.Nil(t, err)

	codec, err := goavro.NewCodec(string(schemaText))
	assert.Nil(t, err)
```

**Comment by oleksmir** [comment] 2019-06-12 04:24
Old schema:
```
{
  "type" : "record",
  "name" : "User",
  "namespace" : "com.github.oleksmir.goavro",
  "fields" : [ {
    "name" : "id",
    "type" : "string",
    "default" : "test_id"
  }, {
    "name" : "age",
    "type" : "int",
    "default" : 100
  } ]
}
```
New schema:
```
{
  "type" : "record",
  "name" : "User",
  "namespace" : "com.github.oleksmir.goavro",
  "fields" : [ {
    "name" : "id",
    "type" : "string",
    "default" : "test_id"
  }, {
    "name" : "age",
    "type" : "int",
    "default" : 100
  }, {
    "name" : "firstName",
    "type" : "string",
    "default" : "test_first_name"
  }, {
    "name" : "lastName",
    "type" : "string",
    "default" : "test_last_name"
  }, {
    "name" : "info",
    "type" : "string",
    "default" : "test_info"
  } ]
}
```
I am trying to read old messages using new schema:
```
file, err := os.Open(newSchemaFilePath)
assert.Nil(t, err)

schemaText, err := ioutil.ReadAll(file)
assert.Nil(t, err)

codec, err := goavro.NewCodec(string(schemaText))
assert.Nil(t, err)

native, _, err := codec.NativeFromBinary(buf.Bytes()) // where buf.Bytes() is my new message
assert.Nil(t, err)
```
`NaviteFromBinary` method returns error `cannot decode binary record "com.github.oleksmir.goavro.User" field "firstName": cannot decode binary string: cannot decode binary bytes: short buffer`

I found tests with the same 'short buffer' check [here](https://github.com/linkedin/goavro/blob/master/bytes_test.go)

**Comment by karrick** [comment] 2019-06-13 17:18
Okay, I understand your comment. Thanks for providing additional information.

Please see this mini rant above how Avro 1.x does not really support schema evolution, in terms of being able to read data encoded with a schema newer than the schema used to encode the data.

https://github.com/linkedin/goavro/issues/140#issuecomment-501796362

**Comment by karrick** [comment] 2019-06-13 17:29
Closing this issue. Feel free to re-open if/when you find evidence that Avro 1.x specification does really support schema evolution.

I'm not trying to be argumentative, but I don't think it's possible using the specification that is published.

**Comment by slaunay** [comment] 2019-07-10 20:53
The fact that schema evolution is not supported with Avro 1.x is quite misleading and will confuse users of this library or Avro in general when hitting the issue described above.

Trying to read some Avro data (raw) without the initial/writer schema is not deterministic indeed and the data can as well be considered garbage, something the Avro specification illustrates as:

> From http://avro.apache.org/docs/1.9.0/spec.html#Schema+Resolution:
A reader of Avro data, whether from an RPC or a file, can always parse that data because the original schema must be provided along with the data.

> From http://avro.apache.org/docs/1.9.0/gettingstartedjava.html#Deserializing
The writer's schema is needed to know the order in which fields were written, while the reader's schema is needed to know what fields are expected and how to fill in default values for fields added since the file was written. If there are differences between the two schemas, they are resolved according to the Schema Resolution specification.

But as long as you have the writer's schema (e.g. header in an Object Container File, schema id in a Kafka record to resolve the original schema) with the Avro payload and a compatible reader's schema (rules applies, no magic here) then you can project an Avro datum from one schema to another and benefit from schema evolution (possibly losing information when a field has been removed, no magic there either).

Another simple example about why the writer schema is mandatory for decoding the data would be to invert the order of the `name` and the `nickname` fields in schema `v1`.
If you do not use the original writer's schema during the projection but the new schema then you would read those two fields as inverted.
But if you provide the original schema (the only valid one) then the library should take care of matching the schema fields ignoring the order (relying on the `name` or the `aliases` properties).

That being said, it makes sense to close this issue not because of a "bug" or an oversight in the Avro specification but rather because of a misusage of the library (providing the reader's schema instead of the writer's schema) as well as a limitation of the library (not being able to provide both a writer and a reader schema and then support schema resolution):

> From http://avro.apache.org/docs/1.9.0/spec.html#Schema+Resolution:
However, the reader may be programmed to read data into a different schema. For example, if the data was written with a different version of the software than it is read, then fields may have been added or removed from records. This section specifies how such schema differences should be resolved.

**Comment by karrick** [comment] 2019-07-11 15:06
You are the first person I’ve spoken with that spent as much or more time actually diving into the specs as I have, and I am grateful that another person sees it.

However, you did shed new light on the topic since I last dove into it, in terms of reading the data with two schemas in hand, the original writer schema and an updated reader schema. While this method of schema evolution would entirely be possible, I find those conversions to be in the realm of an application’s responsibility to thunk data from one schema to another.

I think this realm is worth investigating, but I’ll have to look at this later.

**Comment by slaunay** [comment] 2019-07-11 18:13
> You are the first person I’ve spoken with that spent as much or more time actually diving into the specs as I have, and I am grateful that another person sees it.

Glad to hear that, to be fair the naming for the `default` property is quite confusing.
It is often interpreted as a default value to use when writing a record and not specifying a given field but should actually only be used during schema resolution when a field is not present in the writer's schema to populate the reader's schema field with something.

> While this method of schema evolution would entirely be possible, I find those conversions to be in the realm of an application’s responsibility to thunk data from one schema to another.

Schema evolution is IMHO one of the main features that makes a user pick Avro for exchanging data [1].
Being able to rely on that feature (when implemented) as well as knowing the limitations reduces the complexity involved when dealing with compatibility between schemas which is often a source of subtle bugs (and we can be talking about 10+ different writer schemas to support over the lifetime of an application possibly much more if such data is stored with a very long retention).

The schema registry from Confluent [2] embraces such schema evolution with Avro so that Kafka producers and consumers can evolve at a different pace (one team adds a new field when writing data, another team would then "see" such a new field whenever they "upgrade" their reader's schema).

[1] https://martin.kleppmann.com/2012/12/05/schema-evolution-in-avro-protocol-buffers-thrift.html
[2] https://docs.confluent.io/5.2.2/schema-registry/index.html#schema-management

**Comment by karrick** [comment] 2019-07-11 21:29
Thanks for the links. I'll read them thoroughly when I get a few spare cycles.

**Comment by caevv** [comment] 2019-07-30 15:15
+1 

This is my only blocker to use this library right now. 
The `actgardner/gogen-avro` library does support reader and writer schema evolution deserialisation, but I need a run-time avro deserialisation that this library provides.

> Schema evolution is IMHO one of the main features that makes a user pick Avro for exchanging data [1].
> Being able to rely on that feature (when implemented) as well as knowing the limitations reduces the complexity involved when dealing with compatibility between schemas which is often a source of subtle bugs (and we can be talking about 10+ different writer schemas to support over the lifetime of an application possibly much more if such data is stored with a very long retention).
> 
> The schema registry from Confluent [2] embraces such schema evolution with Avro so that Kafka producers and consumers can evolve at a different pace (one team adds a new field when writing data, another team would then "see" such a new field whenever they "upgrade" their reader's schema).

**Comment by oleksmir** [comment] 2019-07-31 05:01
@slaunay Thanks for a good explanation!

For those who requires schema evolution you can check  `actgardner/gogen-avro` mentioned above. This package support schema evolution starting from v6.1.0. Related issue https://github.com/actgardner/gogen-avro/issues/93.

**Comment by james-johnston-thumbtack** [comment] 2020-04-24 22:03
I am also quite surprised this is not yet supported here, as it seems to be a core requirement to be able to use Avro for any practical purposes with e.g. Kafka.  The links provided by others above regarding schema resolution in the spec, and the details in Confluent Schema Registry provide background on the subject.

Fundamentally one should be able to deserialize using the writer's schema, then project that onto the reader's schema; to me, this is a basic requirement for an Avro package.  It seems odd to me that this package instead takes a stance that the Avro standard is broken in this regards: https://github.com/linkedin/goavro/blob/master/SCHEMA-EVOLUTION.md - to me, this document seems misleading on the matter.

**Comment by actgardner** [comment] 2020-11-04 15:15
@caevv @oleksmir I know this issue is fairly old, but I've implemented generic datum support in gogen-avro as a beta: https://github.com/actgardner/gogen-avro/blob/master/README.md#generic-data. If you're still looking for a library that handles evolution + generic data. Let me know if you have any issues.

**Comment by tmoschou** [comment] 2021-05-06 09:54
It is worth noting that Avro have [updated their documentation](http://avro.apache.org/docs/current/spec.html#schema_record) of `default` to clarify that field values which happen to equal their default must _not_ be omitted in serialisation. 

> `default`: A default value for this field, **only** used when reading instances that lack the field for schema evolution purposes. The presence of a default value does **not** make the field optional at encoding time. Permitted values depend on the field's schema type, according to the table below. Default values for union fields correspond to the first schema in the union. Default values for bytes and fixed fields are JSON strings, where Unicode code points 0-255 are mapped to unsigned 8-bit byte values 0-255. Avro encodes a field **even** if its value is equal to its default.

See also https://issues.apache.org/jira/browse/AVRO-3028

With the example given in https://github.com/linkedin/goavro/blob/master/SCHEMA-EVOLUTION.md, the binary stream, 
```
0x0A, A, l, i, c, e, 0x06, B, o, b, 0x0A, B, r, u, c, e, 0x0A, S, a, l, l, y, 0x06, A, n, n
```
written with
```
Record v0:
    name: string
    nickname: string, default: ""
```
I believe it is actually malformed, as the 3rd record is truncated. If any nickname were to be the empty string, it should be encoded as `0x00`.

**Comment by tneilturner** [comment] 2021-08-10 23:42
Just wanted to chime in here that since 1) We chose Avro since it supports schema evolution and 2) this library is one of the first results that shows up when Googling "Go Avro", and 3) the README still says that "schema evolution is broken in Avro 1.x", maybe we ought to think about updating it with a link to this discussion?  I had to dig into the issues to find it so it could help others who are on a similar path as I am.

**Comment by BryceCicada** [comment] 2021-09-22 09:05
The [README.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/README.md) and the committed file [SCHEMA-EVOLUTION.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/SCHEMA-EVOLUTION.md) are misleading.  

The file [SCHEMA-EVOLUTION.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/SCHEMA-EVOLUTION.md) provides an example of a stream of bytes consisting of multiple serialized avro strings concatenated together.  The description then proposes that the concatenated bytes cannot be deserialized by the avro protocol supporting schema evolution.  The mistakes in the example are:
  - Assuming that avro messages can be concatenated together in this way.  The avro wire format does not provide message boundaries.  Message boundaries are inferred by the presence of the writer schema at the point of deserialization, at which time the consumer knows exactly how the message was serialized and how the serialized bytes correspond to fields in the writer schema.
  - The author appears to assume that providing a default in a schema is sufficient to make the field optional and proposes that this introduces ambiguity in the serialized concatenated bytes.  The use of a default does not make a field optional, it provides an means of evolution if the writer schema omits the field compared to a reader schema against which it is being resolved.

I feel compelled to write this comment because the [README.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/README.md) and [SCHEMA-EVOLUTION.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/SCHEMA-EVOLUTION.md) has lead intelligent people to misunderstand the use of avro on their journey to implement services in go.  

It is, of course, for the repository owner to decide what features are implemented and what files are committed.  If the authors choose not to support schema evolution, so be it.  However, schema evolution works successfully in other language implementations in many production use cases.  I hope that the descriptions above provide some useful feedback and that a change to the  [README.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/README.md) and the committed file [SCHEMA-EVOLUTION.md](https://github.com/linkedin/goavro/blob/d826d47fa7d960e0cc3446895835e3f44e807dc7/SCHEMA-EVOLUTION.md) might be forthcoming.

**Comment by actgardner** [comment] 2022-02-18 22:51
@CarloDeVita This library doesn't support schema evolution as far as I know. To support schema evolution you need to supply both the reader and writer schemas. There are a number of ways to encode the framing of messages and the schema data (like OCF and Single-Object Encoding). gogen-avro supports schema evolution, generic data, and the framing methods: https://github.com/actgardner/gogen-avro#generic-data

**Comment by CarloDeVita** [comment] 2022-02-21 15:25
Hi @actgardner thanks for the answer! The problem is that we don't always know which is the writer schema, because have to support also long jump upgrade (as an example in release 1.1 a field is added, in release 1.2 another field is added -> and we have to upgrade from 1.0 to 1.2 software release). 
We would like to support this type of changes, assigning for example default value to those fields.

**Comment by actgardner** [comment] 2022-02-21 22:18
@CarloDeVita This isn't possible with Avro, because it's an untagged format (there's no metadata about the fields in the serialized messages). You always need to supply the writer schema so the reader knows what fields exist and what types they have. Contrast this with protobuf, which serializes the field number and field type into the message itself. In Avro you need to either serialize the entire schema into the header (OCF) or look it up in a schema registry using some additional metadata.

Martin Kleppman wrote the definitive article about various serialization formats and schema evolution here: https://martin.kleppmann.com/2012/12/05/schema-evolution-in-avro-protocol-buffers-thrift.html

**Comment by CarloDeVita** [comment] 2022-03-01 19:48
@actgardner thank you very much for the support!

**Closed** 2023-02-03 12:01 UTC
Labels: enhancement
