### ISSUE TITLE
Schema canonical-ization breaks with namespace and field names matching inner type names

### ISSUE THREAD

**Issue by Bahkran** [linkedin/goavro#224] opened 2021-02-09 17:03 UTC
I have a schema where a record field shares the name with the type that it relates to:

```json
{
  "fields": [{
    "name": "inner",
    "type": {
      "name": "inner",
      "type": "int"
    }
  }],
  "type": "record",
  "name": "outer",
  "namespace": "x.y.z"
}
```

When producing the canonical schema, there is inconsistent behaviour on whether or not the field name gets prefixed with the namespace. This is due to `pcfObject` iterating over the map without sorting. Depending on the order, `typeLookup` might be modified before or after the field name.

The following test case produces a failure every 10 or so runs.

```
{
    Schema:    `{"fields":[{"name":"inner","type":{"name":"inner","type":"record","fields":[{"name":"dummy","type":"int"}]}}], "type":"record", "name":"outer","namespace":"x.y.z"}`,
    Canonical: `{"name":"x.y.z.outer","type":"record","fields":[{"name":"inner","type":{"name":"x.y.z.inner","type":"record","fields":[{"name":"dummy","type":"int"}]}}]}`,
},
```

I'm not sure of the correct behaviour and had problems reading the spec to see if the field name should be namespaced at all.  Either way, it should be consistent as the Rabin changes with the same schema being passed in.

The fix I have locally is to sort the map before iteration but I'm new to golang and am sure it could be improved.

```
canonical.go: pcfObject()
---

keys := make([]string, 0, len(jsonMap))
for k := range jsonMap {
    keys = append(keys, k)
}
sort.Strings(keys)

for _, k := range keys {
    v := jsonMap[k]
```

**Comment by xmcqueen** [comment] 2022-08-19 22:04
thanks reproduced here:

```ok  	github.com/linkedin/goavro/v2	0.796s
PASS
ok  	github.com/linkedin/goavro/v2	0.690s
PASS
ok  	github.com/linkedin/goavro/v2	0.762s
PASS
ok  	github.com/linkedin/goavro/v2	0.483s
PASS
ok  	github.com/linkedin/goavro/v2	0.754s
PASS
ok  	github.com/linkedin/goavro/v2	0.632s
--- FAIL: TestCanonicalSchema (0.00s)
    canonical_test.go:287: Test failed for schema: {"fields":[{"name":"inner","type":{"name":"inner","type":"record","fields":[{"name":"dummy","type":"int"}]}}], "type":"record", "name":"outer","namespace":"x.y.z"}
        	got canonical:		{"name":"x.y.z.outer","type":"record","fields":[{"name":"x.y.z.inner","type":{"name":"x.y.z.inner","type":"record","fields":[{"name":"dummy","type":"int"}]}}]}
        	expected canonical:	{"name":"x.y.z.outer","type":"record","fields":[{"name":"inner","type":{"name":"x.y.z.inner","type":"record","fields":[{"name":"dummy","type":"int"}]}}]}
FAIL
exit status 1
FAIL	github.com/linkedin/goavro/v2	0.152s
PASS
ok  	github.com/linkedin/goavro/v2	0.661s
```

**Comment by xmcqueen** [comment] 2022-08-20 03:23
I think I've got this fixed. I'll get a PR up for it soon.

**Comment by xmcqueen** [comment] 2022-09-07 17:39
where's my code! OK I'll try to get this going again.

**Comment by xmcqueen** [comment] 2022-09-07 17:49
OK I think this is fixed in the latest release.  It contains the commit where I intended to fix this, and the tests do not show an intermittent failure any more.  Thanks

**Closed by xmcqueen** 2022-09-07 17:49 UTC
